/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkerServicesRouteImport } from './routes/worker.services'
import { Route as WorkerDashboardRouteImport } from './routes/worker.dashboard'
import { Route as WorkerAvailabilityRouteImport } from './routes/worker.availability'
import { Route as WorkerAgendaRouteImport } from './routes/worker.agenda'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientBookRouteImport } from './routes/client.book'
import { Route as ClientAppointmentsRouteImport } from './routes/client.appointments'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkerServicesRoute = WorkerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerAvailabilityRoute = WorkerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerAgendaRoute = WorkerAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => WorkerRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookRoute = ClientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAppointmentsRoute = ClientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ClientRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/worker': typeof WorkerRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/client/appointments': typeof ClientAppointmentsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/worker/agenda': typeof WorkerAgendaRoute
  '/worker/availability': typeof WorkerAvailabilityRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/services': typeof WorkerServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/client/appointments': typeof ClientAppointmentsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/worker/agenda': typeof WorkerAgendaRoute
  '/worker/availability': typeof WorkerAvailabilityRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/services': typeof WorkerServicesRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/worker': typeof WorkerRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/client/appointments': typeof ClientAppointmentsRoute
  '/client/book': typeof ClientBookRoute
  '/client/profile': typeof ClientProfileRoute
  '/worker/agenda': typeof WorkerAgendaRoute
  '/worker/availability': typeof WorkerAvailabilityRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/services': typeof WorkerServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/worker'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/workers'
    | '/auth/login'
    | '/auth/register'
    | '/client/appointments'
    | '/client/book'
    | '/client/profile'
    | '/worker/agenda'
    | '/worker/availability'
    | '/worker/dashboard'
    | '/worker/services'
    | '/admin/'
    | '/client/'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/workers'
    | '/auth/login'
    | '/auth/register'
    | '/client/appointments'
    | '/client/book'
    | '/client/profile'
    | '/worker/agenda'
    | '/worker/availability'
    | '/worker/dashboard'
    | '/worker/services'
    | '/admin'
    | '/client'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/worker'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/workers'
    | '/auth/login'
    | '/auth/register'
    | '/client/appointments'
    | '/client/book'
    | '/client/profile'
    | '/worker/agenda'
    | '/worker/availability'
    | '/worker/dashboard'
    | '/worker/services'
    | '/admin/'
    | '/client/'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  WorkerRoute: typeof WorkerRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/worker/services': {
      id: '/worker/services'
      path: '/services'
      fullPath: '/worker/services'
      preLoaderRoute: typeof WorkerServicesRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/availability': {
      id: '/worker/availability'
      path: '/availability'
      fullPath: '/worker/availability'
      preLoaderRoute: typeof WorkerAvailabilityRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/agenda': {
      id: '/worker/agenda'
      path: '/agenda'
      fullPath: '/worker/agenda'
      preLoaderRoute: typeof WorkerAgendaRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/book': {
      id: '/client/book'
      path: '/book'
      fullPath: '/client/book'
      preLoaderRoute: typeof ClientBookRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/appointments': {
      id: '/client/appointments'
      path: '/appointments'
      fullPath: '/client/appointments'
      preLoaderRoute: typeof ClientAppointmentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminWorkersRoute: AdminWorkersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientAppointmentsRoute: typeof ClientAppointmentsRoute
  ClientBookRoute: typeof ClientBookRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAppointmentsRoute: ClientAppointmentsRoute,
  ClientBookRoute: ClientBookRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface WorkerRouteChildren {
  WorkerAgendaRoute: typeof WorkerAgendaRoute
  WorkerAvailabilityRoute: typeof WorkerAvailabilityRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  WorkerServicesRoute: typeof WorkerServicesRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerAgendaRoute: WorkerAgendaRoute,
  WorkerAvailabilityRoute: WorkerAvailabilityRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  WorkerServicesRoute: WorkerServicesRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  WorkerRoute: WorkerRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
